### ISSUE TITLE
Misleading warning message for disabling daemon

### ISSUE THREAD

**Issue by furkanmustafa** [ddccontrol/ddccontrol#116]
When dbus connection fails, ddccontrol [gives a hint](https://github.com/ddccontrol/ddccontrol/blob/c9584048f16b539069af432c4b116eccb2bf72e6/src/ddccontrol/main.c#L288); 

```
Failed to open D-Bus proxy, try with DDCCONTROL_NO_DBUS=1.
```

But the [actual env var is `DDCCONTROL_NO_DAEMON`](https://github.com/ddccontrol/ddccontrol/blob/c9584048f16b539069af432c4b116eccb2bf72e6/src/ddccontrol/main.c#L145).

Please see here https://github.com/ddccontrol/ddccontrol/issues/37#issuecomment-807538048

**Comment by larstobi** [comment]
Thanks!
