### ISSUE TITLE
Device changing with every reboot

### ISSUE THREAD

**Issue by cpfaff** [ddccontrol/ddccontrol#130]
He there. Thanks for the hard work on this nice tool by the way. I have been using it after I created a profile for my dell monitor for many months without any issues. However since a while I have the problem that on every reboot the device is a different one. That makes it harder to be used in a scripted solution bound to shortcuts. Do you have any idea why this could be and how I could avoid that from happening. I am on Arch Linux.

**Comment by larstobi** [comment]
Device name creation seems to be done by systemd and udev. I would suggest trying to set up a `SYSTEMD_ALIAS` or a `udev` rule.

**Comment by cpfaff** [comment]
Ok that is a good point. I will give this a try. Thanks! When I found a workaround I will share it here. Just in case anybody else comes across the same problem.

**Comment by cpfaff** [comment]
In the end this is possible with some effort using udev. I decided however to with a more easy solution for now. See for reference the https://bbs.archlinux.org/viewtopic.php?id=278556
