### ISSUE TITLE
Request Manjaro Linux Release

### ISSUE THREAD

**Issue by AntonioBerna** [ddccontrol/ddccontrol#168]
In my package manager there is only version 0.6.0 which came out in 2021. Would it be possible to create a release for major Linux distributions? Thanks

**Comment by genodeftest** [comment]
Hi @AntonioBerna, can you please ask this in the Manjaro forums instead?

Also, I [couldn't find ddccontrol in Manjaro's package database](https://packages.manjaro.org/?query=ddccontrol). Is it possible that this package has been removed from Manjaro? If that is the case, they will probably search for someone to package ddccontrol for Manjaro and maintain it. You might want to consider volunteering for this.

**Comment by AntonioBerna** [comment]
Hi, thank you for the reply. I just checked and they actually fixed everything I just didn't notice. I'll leave you the screenshot as proof of this.

![screenshot](https://github.com/ddccontrol/ddccontrol/assets/60107274/32a986e3-f817-4c1a-98a0-0c3e47692fdd)
