### ISSUE TITLE
I/O warning : failed to load external entity "/usr/local/share/ddccontrol-db/options.xml"

### ISSUE THREAD

**Issue by mailinglists35** [ddccontrol/ddccontrol#23]
I see no `options.xml` file neither in the cloned git source dir nor in `/usr/local` ; the app complains about missing options.xml

Where do I get the options.xml file from?

(installed without prefix=/usr and let configure default to /usr/local)

**Comment by mailinglists35** [comment]
user@host:~$ ddccontrol -p
ddccontrol version 0.4.3
Copyright 2004-2005 Oleg I. Vdovikin (oleg@cs.msu.su)
Copyright 2004-2006 Nicolas Boichat (nicolas@boichat.ch)
This program comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of this program under the terms of the GNU General Public License.

I/O warning : failed to load external entity "/usr/local/share/ddccontrol-db/options.xml"
Document not parsed successfully.
Failed to initialize ddccontrol database...
Unable to initialize ddcci library.

**Comment by mailinglists35** [comment]
user@host:/usr/local/src/ddccontrol$ find .|grep -i options
./m4/ltoptions.m4

**Comment by mailinglists35** [comment]
followed exactly the instructions from source
https://github.com/ddccontrol/ddccontrol#installation-from-sources
with ./cofnigure instead of configure prefix=/usr

**Comment by mailinglists35** [comment]
ubuntu 16.04

**Comment by kravemir** [comment]
I'll update the documentation for manual installation. Sorry for trouble caused by not having that information in there.

**Comment by kravemir** [comment]
I have updated README.md.
