### ISSUE TITLE
please oh mercy do not blink on me

### ISSUE THREAD

**Issue by anarcat** [ddccontrol/ddccontrol#24]
ddccontrol currently sends the following escape sequence to make sure it *reaaaally* have the user's attention, which you can test with printf:

```
printf "\x1B[5;31mBLINKING RED\x1B[0m\n"
```

this will show the words in BLINKING RED. the red part is fine, but the blinking makes it really hard to actually *read* the darn notice. we can certainly tell something is wrong, but it's horribly hard to read.

can we turn that thing off please? :) i believe the better escape sequence is:

```
printf "\x1B[0;31mJUST PLAIN RED THANKS!\x1B[0m\n"
```

**Comment by kravemir** [comment]
Well, it doesn't blink for me, which terminal do you use?

**Comment by anarcat** [comment]
rxvt-unicode.

**Comment by kravemir** [comment]
Yes, this terminal blinks. Agree, it's horrible to read the blinking text.

**Comment by anarcat** [comment]
i'll send a PR.

**Comment by kravemir** [comment]
I've merged the PR, will release it with the next version.
