### ISSUE TITLE
D-Bus system daemon

### ISSUE THREAD

**Issue by kravemir** [ddccontrol/ddccontrol#25]
DDCControl requires access to system resources to control monitors.

Access can't be easily granted to all i2c devices, as they might not be monitor devices, and some data sequences could be harmful to i2c devices. Therefore, regular users would be able to send requests to daemon, and daemon will process only valid requests: i2c device is monitor, send only DDC commands.

This will fix #5 and #12. And could solve #18, as daemon could cache stuff, like EDID.

**Comment by kravemir** [comment]
There's ongoing work in branch daemon of the fork https://github.com/kravemir/ddccontrol/tree/daemon. It will be merged, after work is done.

**Comment by cheater** [comment]
Why is a daemon necessary for this? A library can check this just as well. A daemon will make this unnecessarily complex, especially when you start integrating with dbus.

**Comment by StefanBruens** [comment]
Because a daemon can run with different privileges than the calling implementation.

Have a look at e.g. udisks2, upower, ...

**Comment by kravemir** [comment]
Implemented in #34

**Comment by kravemir** [comment]
@cheater also, if you have applets. And, change brightness or something with keybinding, or a command. Then applets can be notified about changes, and update themselves.
