### ISSUE TITLE
Coudn't build ddccontrol on Ubuntu 14.10

### ISSUE THREAD

**Issue by max-kammerer** [ddccontrol/ddccontrol#3]
Making all in src
make[1]: Entering directory '/home/mike/devel/tools/dcc/ddccontrol/src'
make  all-recursive
make[2]: Entering directory '/home/mike/devel/tools/dcc/ddccontrol/src'
Making all in lib
make[3]: Entering directory '/home/mike/devel/tools/dcc/ddccontrol/src/lib'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/mike/devel/tools/dcc/ddccontrol/src/lib'
Making all in ddccontrol
make[3]: Entering directory '/home/mike/devel/tools/dcc/ddccontrol/src/ddccontrol'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/mike/devel/tools/dcc/ddccontrol/src/ddccontrol'
Making all in gddccontrol
make[3]: Entering directory '/home/mike/devel/tools/dcc/ddccontrol/src/gddccontrol'
Makefile:787: **\* missing separator (did you mean TAB instead of 8 spaces?).  Stop.
make[3]: Leaving directory '/home/mike/devel/tools/dcc/ddccontrol/src/gddccontrol'
Makefile:404: recipe for target 'all-recursive' failed
make[2]: **\* [all-recursive] Error 1
make[2]: Leaving directory '/home/mike/devel/tools/dcc/ddccontrol/src'
Makefile:342: recipe for target 'all' failed
make[1]: **\* [all] Error 2
make[1]: Leaving directory '/home/mike/devel/tools/dcc/ddccontrol/src'
Makefile:420: recipe for target 'all-recursive' failed
make: **\* [all-recursive] Error 1

**Comment by hmvs** [comment]
@max-kammerer hi. have you found the way how to build it?

**Comment by max-kammerer** [comment]
@hmvs, no, i haven't. 
But binaries from old Ubuntu works on new one http://packages.ubuntu.com/wily/ddccontrol

**Comment by hmvs** [comment]
@max-kammerer thanks.

**Comment by Gluttton** [comment]
It's looks like such error is the consequence of unsuccessful calling of `autogen.sh`. Please pay attention that `autoget.sh` performed without any errors (note that `Makefile` is created anyway even if `autoget.sh` has been performed with errors).

**Comment by mirh** [comment]
Is this fixed by #1?

**Comment by Gluttton** [comment]
No. 
It looks like:
> It's looks like such error is the consequence of unsuccessful calling of autogen.sh. Please pay attention that autoget.sh performed without any errors (note that Makefile is created anyway even if autoget.sh has been performed with errors).

**Comment by mirh** [comment]
Mhh.. #4 perhaps then?

**Comment by cheater** [comment]
FYI, packages from the latest Ubuntu proposed just work on 14.04, so you should be able to just get them. It all comes down to libc compat, and that's met by the version in older Ubuntu's.

**Comment by kravemir** [comment]
Closing the issue. Ubuntu 14.10 Utopic Unicorn reached the end of its life on July 23, 2015.

However, Ubuntu successfully builds on trusty, it's done by TravisCI.
