### ISSUE TITLE
D-Bus connection failed

### ISSUE THREAD

**Issue by guzzard** [ddccontrol/ddccontrol#36]
Getting this error:
```
D-Bus connection failed with error: Error calling StartServiceByName for ddccontrol.DDCControl: GDBus.Error:org.freedesktop.DBus.Error.TimedOut: Failed to activate service 'ddccontrol.DDCControl': timed out (service_start_timeout=25000ms).
```

After the error message/timeout ddccontrol continues, but it means any command has a delay of 25 sec which is a bit annoying.

**Comment by kravemir** [comment]
Did you follow complete installation steps: https://github.com/ddccontrol/ddccontrol#installation-from-sources ?

If so, please provide output of following commands:

```
find /etc/dbus-1/ -name "*ddc*"
find /usr/share/dbus-1/ -name "*ddc*"
```

**Comment by guzzard** [comment]
@kravemir, sorry should have provided a bit more information.

Built master at commit 7a7cdb4 using this [AUR package](https://aur.archlinux.org/packages/ddccontrol-git). As far as I can tell the only difference is the configure line.

Readme: ./configure --prefix=/usr/ --sysconfdir=/etc --libexecdir=/usr/lib
AUR package: ./configure --prefix=/usr

But should not have any effect since /etc and /usr/lib are the default paths on Arch?

The find commands returned this:
```
$ find /etc/dbus-1/ -name "*ddc*" <-- returned nothing
$ find /usr/share/dbus-1/ -name "*ddc*"
/usr/share/dbus-1/system-services/ddccontrol.DDCControl.service
/usr/share/dbus-1/interfaces/ddccontrol.DDCControl.xml
```

**Comment by kravemir** [comment]
Well, it's missing configuration, which allows regular users to invoke methods on the daemon: https://github.com/ddccontrol/ddccontrol/blob/7a7cdb454697e920fb11479b531d36f31b70b609/src/daemon/data/ddccontrol.DDCControl.conf

It should be installed by following Makefile rule:

https://github.com/ddccontrol/ddccontrol/blob/7a7cdb454697e920fb11479b531d36f31b70b609/src/daemon/data/Makefile.am#L3-L4

I don't use Arch (anymore), so I can't test it manually (in short time, as I would had to install whole OS). Please, provide the list of files installed by that package. It should be `pacman -Ql ddccontrol-git`, if I'm not wrong.

**Comment by guzzard** [comment]
Thanks! Found the issue, ddccontrol.DDCControl.conf ended up in /usr/etc instead of /etc by default. Added --sysconfdir=/etc, and now everything works fine! Will ask the package maintainer to update the PKGBUILD.

**Comment by Konfekt** [comment]
The same issue occurs with version 0.60 from https://build.opensuse.org/package/binaries/hardware/ddccontrol/15.4. 

The following files are included:

```
usr/
| bin/
| | ddccontrol
| lib/
| | ddccontrol/
| | | ddccontrol_service
| | modules-load.d/
| | | ddccontrol-i2c-dev.conf
| | systemd/
| | | system/
| | | | ddccontrol.service
| share/
| | dbus-1/
| | | interfaces/
| | | | ddccontrol.DDCControl.xml
| | doc/
| | | packages/
| | licenses/
| | | ddccontrol/
| | man/
| | | man1/
```
