### ISSUE TITLE
BenQ BL2420PT data

### ISSUE THREAD

**Issue by Evi1M4chine** [ddccontrol/ddccontrol#8]
Here is the complete data for this screen:

~ $ LANG= LC_ALL= ddccontrol -p -c -d 
ddccontrol version 0.4.2
Copyright 2004-2005 Oleg I. Vdovikin (oleg@cs.msu.su)
Copyright 2004-2006 Nicolas Boichat (nicolas@boichat.ch)
This program comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of this program under the terms of the GNU General Public License.

Probing for available monitors.....I/O warning : failed to load external entity "/usr/share/ddccontrol-db/monitor/BNQ801B.xml"
Document not parsed successfully.
I/O warning : failed to load external entity "/usr/share/ddccontrol-db/monitor/BNQlcd.xml"
Document not parsed successfully.
.....
Detected monitors :
 - Device: dev:/dev/i2c-4
   DDC/CI supported: Yes
   Monitor Name: VESA standard monitor
   Input type: Digital
  (Automatically selected)
Reading EDID and initializing DDC/CI at bus dev:/dev/i2c-4...
I/O warning : failed to load external entity "/usr/share/ddccontrol-db/monitor/BNQ801B.xml"
Document not parsed successfully.
I/O warning : failed to load external entity "/usr/share/ddccontrol-db/monitor/BNQlcd.xml"
Document not parsed successfully.

EDID readings:
        Plug and Play ID: BNQ801B [VESA standard monitor]
        Input type: Digital
=============================== WARNING ===============================
There is no support for your monitor in the database, but ddccontrol is
using a basic generic profile. Many controls will not be supported, and
some controls may not work as expected.
Please update ddccontrol-db, or, if you are already using the latest
version, please send the output of the following command to
ddccontrol-users@lists.sourceforge.net:

LANG= LC_ALL= ddccontrol -p -c -d

Thank you.
=============================== WARNING ===============================

Capabilities:
Raw output: (prot(monitor)type(lcd)model(BL2420PT)cmds(01 02 03 07 0C E3 F3)vcp(02 04 05 08 0B 0C 10 12 14(04 05 08 0B) 16 18 1A 52 72(50 64 78 8C A0) 86(01 02 05) 87 8A 90 AA(01 02 FF) AC AE B2 B6 C0 C6 C8 C9 CA(01 02) CC(01 02 03 04 05 06 08 09 0A 0B 0D 12 14 1A 1E 1F 20) D6(01 04) D8 DA(00 02) DC(00 03 0B 0C 0E 0F 10 11 12 13 14) DF E2(00 01) E3(00 01) E7(00 01) E8(00 01) E9(00 01 02 03) EA(00 01 02 03 04 05) EF(00 01) F0(00 01 02) F1(00 01) F2(14 28 3C 50 64) F4(00 01) F5(00 01) F6(00 01) F7(00 01) F8(00 0A 14 1E) F9 60(01 03 11 0F) 62 8D(01 02) FF)mswhql(1)mccs_ver(2.2)asset_eep(40)mpu_ver(01))
Parsed output: 
        VCP: 02 04 05 08 0b 0c 10 12 14 16 18 1a 52 60 62 72 86 87 8a 8d 90 aa ac ae b2 b6 c0 c6 c8 c9 ca cc d6 d8 da dc df e2 e3 e7 e8 e9 ea ef f0 f1 f2 f4 f5 f6 f7 f8 f9 ff 
        Type: LCD

Controls (valid/current/max) [Description - Value name]:
Control 0x02: +/1/255 C [Secondary Degauss - Secondary Degauss]
Control 0x04: +/0/1 C [Restore Factory Defaults]
Control 0x05: +/0/1 C [Restore Brightness and Contrast]
Control 0x08: +/0/1 C [Restore Factory Default Color]
Control 0x0b: +/50/65535 C [???]
Control 0x0c: +/70/126 C [???]
Control 0x10: +/50/100 C [Brightness]
Control 0x12: +/50/100 C [Contrast]
Control 0x14: +/5/11 C [???]
Control 0x16: +/100/100 C [Red maximum level]
Control 0x18: +/100/100 C [Green maximum level]
Control 0x1a: +/100/100 C [Blue maximum level]
Control 0x52: +/0/255 C [???]
Control 0x60: +/3/3 C [Input Source Select - Digital]
Control 0x62: +/100/100 C [Audio Speaker Volume Adjust]
Control 0x6c: +/50/100   [???]
Control 0x6e: +/50/100   [???]
Control 0x70: +/50/100   [???]
Control 0x72: +/120/160 C [???]
Control 0x86: +/2/5 C [???]
Control 0x87: +/5/10 C [???]
Control 0x8d: +/2/2 C [???]
Control 0xaa: +/2/100 C [OSD Orientation - Portrait]
Control 0xac: +/23264/65281 C [???]
Control 0xae: +/6000/65535 C [???]
Control 0xb2: +/1/8 C [???]
Control 0xb5: +/0/255   [???]
Control 0xb6: +/3/4 C [???]
Control 0xc0: +/168/65535 C [???]
Control 0xc6: +/60/65535 C [???]
Control 0xc8: +/18/65535 C [???]
Control 0xc9: +/7/65535 C [???]
Control 0xca: +/2/2 C [???]
Control 0xcc: +/4/255 C [???]
Control 0xd6: +/1/4 C [DPMS Control - On]
Control 0xd8: +/6/6 C [???]
Control 0xdc: +/0/19 C [???]
Control 0xdf: +/513/65535 C [???]
Control 0xe2: +/1/1 C [???]
Control 0xe3: +/0/1 C [???]
Control 0xe7: +/0/255 C [???]
Control 0xe8: +/0/255 C [???]
Control 0xe9: +/0/3 C [???]
Control 0xef: +/1/1 C [???]
Control 0xf0: +/1/2 C [???]
Control 0xf1: +/0/1 C [???]
Control 0xf2: +/1300/6500 C [???]
Control 0xf5: +/1/3 C [???]
Control 0xf6: +/1/1 C [???]
Control 0xf7: +/0/1 C [???]
Control 0xf8: +/0/30 C [???]
Control 0xf9: +/1/10 C [???]
Control 0xfc: +/1/1   [???]
Control 0xfe: +/0/255   [???]
Control 0xff: +/0/1 C [???]

**Comment by larstobi** [comment]
Kamino closed and cloned this issue to larstobi/ddccontrol-db

**Comment by larstobi** [comment]
Moved to ddccontrol/ddccontrol-db
