### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by pabs3** [ddccontrol/ddccontrol#87]
ddccontrol is about to be removed from Debian bullseye because of [Debian#957127](https://bugs.debian.org/957127) about the build failure with GCC 10, which was reported upstream in #74 and fixed in #80. It would be great if there could be a new release so that we can keep ddccontrol in Debian bullseye by fixing the build failure using a new upstream release instead of backporting the patch.

**Comment by pabs3** [comment]
I have just done a non-maintainer upload of ddccontrol to fix the issue and prevent removal of ddccontrol from Debian bullseye.

A new release would still be appreciated though, there have been a lot of improvements since the last one in 2018.

**Comment by larstobi** [comment]
Good idea. I'll make a release.

**Comment by pabs3** [comment]
Would you mind fixing the build failure when <sys/io.h> is missing
first (#88)? Then the new release could get into bullseye, but if it
doesn't get fixed then I'll have to make a patch.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by larstobi** [comment]
@pabs3 https://github.com/ddccontrol/ddccontrol/releases/tag/0.5.0

**Comment by pabs3** [comment]
Kind of. There was a new release, but it didn't fix all the build
failures, for that we need #88 fixed by merging PR #94 into master and
then making a new release from that. Merging the other build failure
fixes in PR #98 is going to be needed too.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by larstobi** [comment]
@pabs3 All of the listed PRs are now merged and version 0.5.2 is released.

**Comment by pabs3** [comment]
Thanks! I have filed a request to update the Debian ddccontrol package:

https://bugs.debian.org/988113

PS: In case you are interested there are some other bugs that could
cause removal of ddccontrol from Debian in the future:

Switch gddccontrol from GTK 2 to 3 or 4:

http://bugs.debian.org/967304

Build failure when libxml2 removes xml2-config:

http://bugs.debian.org/949090

Some of the other bug reports may be of interest to you:

http://bugs.debian.org/src:ddccontrol

-- 
bye,
pabs

https://bonedaddy.net/pabs3/
