### ISSUE TITLE
build failure on 32-bit ARM with glibc 2.30 and later

### ISSUE THREAD

**Issue by pabs3** [ddccontrol/ddccontrol#88]
ddccontrol fails to build on 32-bit ARM with glibc 2.30 and later because sys/io.h has been removed from glibc on those platforms:

https://buildd.debian.org/status/package.php?p=ddccontrol

From the glibc NEWS file:

```
Version 2.30
...
Deprecated and removed features, and other changes affecting compatibility:
...
* On 32-bit Arm, support for the port-based I/O emulation and the <sys/io.h>
  header have been removed.
```

**Comment by pabs3** [comment]
The correct thing to do would be port the `intel740`, `intel810` and `sis` code away from x86 I/O ports to architecture-neutral Linux interfaces for device access.

If the hardware supported by the `intel740`, `intel810` and `sis` drivers are not on discrete GPUs that can be plugged into a PCI/PCIe slot on any CPU architecture with PCI support, then porting away from x86 I/O ports would not be useful so a workaround would be reasonable.

Since older versions of glibc still have the header, other arches still have the header and other libcs like musl still have the header on the ARM ports, I think the best available workaround would be to check if <sys/io.h> is available and only use the `intel740`, `intel810` and `sis` drivers when the header is available.

**Comment by larstobi** [comment]
@pabs3 Sounds like a good workaround. Are you able to provide a PR for it?

**Comment by pabs3** [comment]
I'm a bit too busy at the moment so I'd prefer if the maintainers could do it instead.

**Comment by pabs3** [comment]
PS: The [Debian#979283](https://bugs.debian.org/979283) bug got filed about this.

**Comment by larstobi** [comment]
All right. `armhf`, that's the Raspberry Pi 2 and friends, is it? Not sure I have one of those lying around, but I'll check.

I too am very busy at the moment, so it won't be the first thing I'm able to prioritize. I will at least state it here when I start working on it. (if I haven't written any comment about it here, I have not started).

**Comment by pabs3** [comment]
Yes, but you can also just test on amd64 by manually removing the
<sys/io.h> file from your system before trying to build ddccontrol.
