### ISSUE TITLE
ddcci.c:1207]: (error) Memory leak: filename

### ISSUE THREAD

**Issue by larstobi** [ddccontrol/ddccontrol#9]
> created by dcb, imported from https://sourceforge.net/p/ddccontrol/monitor-support-requests/10/

Source code is

```
if (stat(filename, &buf) < 0) {
    if (errno != ENOENT) {
        perror(_("Error while getting informations about ddccontrol home directory."));
        return 0;
```

**Comment by eagleivg** [comment]
Fixed: https://github.com/ddccontrol/ddccontrol/pull/16#issuecomment-313610568
