### ISSUE TITLE
build failure when libxml2 removes xml2-config 

### ISSUE THREAD

**Issue by pabs3** [ddccontrol/ddccontrol#91]
Forwarding [Debian ddccontrol#949090](https://bugs.debian.org/949090):

Debian is planning on removing `xml2-config` from `libxml2`, which will cause a build failure in ddccontrol when it happens.

Please switch from `xml2-config` for detecting `libxml2` to `pkg-config` instead, via the `PKG_CHECK_MODULES` macro.

**Comment by barak** [comment]
0.5.2-2, just uploaded to Debian, has a patch for this issue. I've just opened a pull request to address this, and two other small problems.

**Comment by larstobi** [comment]
PR #108 merged, version [0.5.3](https://github.com/ddccontrol/ddccontrol/releases/tag/0.5.3) is released. Hope that fixes this.

**Comment by pabs3** [comment]
The builds succeeded, thanks.
