### ISSUE TITLE
Systemd unit not being installed leading to missing dbus peer (Fedora 33)

### ISSUE THREAD

**Issue by n8mensch** [ddccontrol/ddccontrol#92]
Hi,

In case anyone else with Fedora 33+ has this issue: Using ddccontrol in any form (cli, gui) leads to the following error:
`Probe failed: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer`

The cause is the missing systemd-unit not being installed by Fedora's 33+ rpms, as the service-file is not generated at all. My assumption is that either the detection is failing around https://github.com/ddccontrol/ddccontrol/blob/c9584048f16b539069af432c4b116eccb2bf72e6/configure.ac#L283 or the rpm building script (enviroment, etc.) must enforce systemd with a configure argument.

Workaround: Manually create a fitting `ddccontrol.service` in `/usr/lib/systemd/system` and `systemctl enable` the service to be automatically started.

Sorry if this is the wrong place for the issue but I think people (google) might be searching here first.

**Comment by joy4eg** [comment]
I created a bug for fedora: https://bugzilla.redhat.com/show_bug.cgi?id=1917264

**Comment by larstobi** [comment]
Fixed by https://src.fedoraproject.org/rpms/ddccontrol/pull-request/1

**Comment by martin-ueding** [comment]
@n8mensch: What would such a fitting service file look like?

**Comment by n8mensch** [comment]
Sorry for the long delay - I'm not an active GH user...

Basically https://github.com/ddccontrol/ddccontrol/tree/master/src/daemon/data has everything one needs. Both the dbus-service incl. config and the systemd-service file to have the dbus-service managed by systemd (via redirection?).

Once the "incorrect" version is installed, drop [ddccontrol.service.in](https://github.com/ddccontrol/ddccontrol/blob/master/src/daemon/data/ddccontrol.service.in) as `ddccontrol.service` your system.d directory (`/usr/lib/systemd/system` in my case) and replace `@servicedir@` within it to where the service binary has been installed.

If I'm not mistaken the dBus part was installed correctly.
